### PR TITLE
Improve updater

### PR DESCRIPTION
**Pull request by LinuxClient**
Improve updater by adding "try-with-resources", missing braces and lambda expressions. I also removed unnecessary assignments.

### CODE REVIEW

**Comment by LinuxClient** [comment]
1. Once a variable has been initialized, it can no longer be changed. Since they are not overwritten anywhere, the highest priority is to create clarity.
2. To improve clarity and prevent bugs like [Apple's goto bug](https://dwheeler.com/essays/apple-goto-fail.html#targetText=On%202014%2D02%2D21%20Apple,fail%20goto%20fail%E2%80%9D%20vulnerability).
3. What line are you talking about?

**Comment by CuukyOfficial** [comment]
1. Yeah I'm familiar with the use of the final modifiers, but I only use it if there is a special reason why it shouldn't be changed (for example in calculations or constants), otherwise I just let the compiler do its job.
2. I've never made bugs like this before, if you format your code right you won't make that kind of mistakes
3. VaroUpdateResultSet:23

**Comment by LinuxClient** [comment]
You can do that, yes. However, it provides a nicer structure just like partitioning variables of the same type. To point number 2: You can accidentally produce bugs with it, but it is not a must. However, any experienced developer will tell you that this application is much clearer and more beautiful. Writing code quickly is one thing, good and beautiful code is another.

**Comment by CuukyOfficial** [comment]
I don't really agree with the code style changes, the lambda change and the "try-with-resources" is good tho. If you could change that I'd accept the pull request.

**Comment by LinuxClient** [comment]
[The revised memory model proposed by JSR 133 includes special provisions for final fields, provisions that are absent from the existing specification. Newer VMs already implement this specification, and treat final fields accordingly. Because final fields are assigned exactly once, aggressive optimizations in a multithreaded context become possible. Specifically, a field doesn't need to be ever reloaded, since its value is guaranteed never to change.](https://archive.vn/JK92l#selection-549.1-549.455)

**Comment by CuukyOfficial** [comment]
Okay maybe that's a good point, I will change that in a later recode of this project. Still, the brackets and the declarations are still a problem for me

**Comment by LinuxClient** [comment]
As I have already said, the braces will not produce errors from future developers.

**Comment by CuukyOfficial** [comment]
I prefer not using the braces in such cases, it looks nicer - it's personal preference. 
Same thing with the declaration

**Comment by LinuxClient** [comment]
Does it look better now?

**Comment by CuukyOfficial** [comment]
That's more like it. But why did your remove the private modifiers in the enums?

**Comment by LinuxClient** [comment]
No matter which modifier a constructor of an enum has, it can only be called within the class. Therefore you always take package-private.

**Comment by CuukyOfficial** [comment]
Yeah I know that, but I want to have a modifier in front of a constructor - personal preference

**Comment by LinuxClient** [comment]
Why do you use so many unnecessary things?

**Comment by LinuxClient** [comment]
The code is very inefficient, there are memory leaks, performance problems and it is mostly hardcoded.
And why do you have something like that in your code:
`if (configurations.containsKey(section.getFolder() + "/" + section.getName())) {
				System.out.println(Main.getConsolePrefix() + "PAUL NEIN");
				Bukkit.getServer().shutdown();
			}`

**Comment by CuukyOfficial** [comment]
It's a joke - a contributor once made a mistake which cost me hours of fixing, so I made this.
And if you think that this code is performing badly, why don't you prove that to me instead of just dropping random statements

**Comment by CuukyOfficial** [comment]
And there are many things in this code that I don't like anymore (like a bad structure, final etc). But until I didn't recode it, I won't change things in order to keep things simple and similar.

**Comment by LinuxClient** [comment]
De uses multiple nested loops, which are executed synchronously. The same is true for MySQL: there you use statements instead of prepared statements, which are faster and more secure against SQL injections. Also MySQL is never executed asynchronously. With a high probability you have several entries in the table from one player.

**Comment by CuukyOfficial** [comment]
I didn't knew I don't use prepared statements, I thought I would. Still, this won't make any noticeable difference in performance, but I will change that.
And the main game loop for example has to be synchronized - Bukkit doesn't like handling the players asynchronously and even that doesn't cost any performance.

**Comment by LinuxClient** [comment]
When you execute something synchronously, you wait for it to finish before moving on to another task. When you execute something asynchronously, you can move on to another task before it finishes.

**Pull request closed without merging**
