### PR TITLE
moved to gradle

### PR DESCRIPTION
**Pull request by bestlinuxgamers**
added dependencies
optimized .gitignore

### CODE REVIEW

**Comment by bestlinuxgamers** [comment]
Since almost all files have been moved, there will be a very high probability of conflicts with a new commit. Therefore this pull request should be reviewed as soon as possible. @CuukyOfficial

**Comment by CuukyOfficial** [comment]
Gradle already implemented

**Comment by bestlinuxgamers** [comment]
Just for the record: The feature was not implemented at the time of the pull request and the corresponding pull request did not exist yet. The owner seemed to think it made more sense to redo everything instead of providing feedback or requesting changes.

**Comment by CuukyOfficial** [comment]
> Just for the record: The feature was not implemented at the time of the pull request and the corresponding pull request did not exist yet. The owner seemed to think it made more sense to redo everything instead of providing feedback or requesting changes.

Yes, this implementation didn't meet my expectations. Of course I could've provided you with further instructions to make this transition fitting my requirements (static paths to jars, moving the src folder, ...). @Almighty-Satan then said to me that he could do this for me very quickly - I didn't mean to disrespect you in any way. This was just a more qick way.

**Pull request closed without merging**
