### PR TITLE
Update PlayerChatListener.java

### PR DESCRIPTION
**Pull request by Kalibrier**
Should fix the "Could not pass event AsyncPlayerChatEvent" error

### CODE REVIEW

**Comment by Almighty-Satan** [comment]
This does not work as is.

without this patch:
image
with this patch:
image

Setting the format to `%2$s` should fix this.

**Comment by Almighty-Satan** [comment]
On second thought I'm not sure if we should modify the message at all as this might interfere with other plugins that rely on the AsyncPlayerChatEvent. It would be better to properly escape all special characters and just set the format string

**Comment by Kalibrier** [comment]
👍

**Comment by Almighty-Satan** [comment]
This has been fixed in https://github.com/CuukyOfficial/VaroPlugin/commit/29b090e610036c9e8bd5f120f9427b777669ed53, but that version won't be released any time soon. You could either close this PR, or if you want to, backport the fix (just cancel the event and broadcast the message instead of using `setFormat`) .

**Comment by Almighty-Satan** [comment]
Fixed in 9e400d66d2fcb3522823d19aa61704ee02aa780a

**Pull request closed without merging**
